# _page_layout.html: Autogenerated file start
def render(name,header,footer,layout,vars):
    yield """<!DOCTYPE html>
<html lang=\"en\">
"""
# _html_head.html: Autogenerated file start
    def render1(name):
        yield """<head>
    <meta charset='utf-8'/>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>Fellsafe CP"""
        if name is not None:
            yield """-"""
            yield str(name)
        yield """</title>
    <link rel='stylesheet' href='/static/fellsafe.css' type='text/css'/>
    <script src='/static/fellsafe.js' type='text/javascript'></script>
</head>
"""
# _html_head.html: Autogenerated file end
    yield from render1(name)
    yield """<body>
"""
    if header is not None:
        yield """<header class='fs-header'>"""
        yield str(header)
        yield """</header>
"""
    if layout is not None:
        if vars is None:
            _ = __import__('fellsafe.templates.'+layout.replace('.','_'),None,None,1)
            yield from _.render()
        else:
            _ = __import__('fellsafe.templates.'+layout.replace('.','_'),None,None,1)
            yield from _.render(vars)
    if footer is not None:
        yield """<footer class='fs-footer'>"""
        yield str(footer)
        yield """</footer>
"""
    yield """</body>
</html>
"""
# _page_layout.html: Autogenerated file end
